#!/bin/bash
clear
cd
figlet Minecraft Pro 
if [ "$?" == "127" ]; then
clear 
echo Figlet not detected 
echo Download figlet? [y,n]
read -rsn1 input
if [ "$input" == "y" ]; then
sudo apt-get -y install figlet
OpenMinecraft
fi
fi
clear
figlet Minecraft Pro
echo 1. Launch
echo 2. Launch Options -Debug-
echo 3. Advanced Settings -Login-
echo 4. Credits
echo 5. Installation troubleshoot
echo 6. Update Launcher
echo "(C)lose"
read -rsn1 input
if [ "$input" == "1" ]; then
echo Opening Minecraft
echo Keep settings all the way down!
echo Keep window default size for best performance!
sleep 2
cd Minecraft && ./runMC1_12_2_OptifineF4.sh
fi
if [ "$input" == "2" ]; then
java -jar Minecraft/Minecraft.jar
fi
if [ "$input" == "3" ]; then
sudo nano Minecraft/runMC1_12_2_OptifineF4.sh
fi
if [ "$input" == "s" ]; then
echo You best not ruin it!
read -rsn2 input
if [ "$input" == "ok" ]; then
clear
echo ACCESS GRANTED
echo "<     >"
sleep 3
clear
echo ACCESS GRANTED
echo "<===  >"
sleep 1
clear
echo ACCESS GRANTED
echo "<=====>"
sleep 2
clear
sudo nano /usr/bin/OpenMinecraft
fi
fi
if [ "$input" == "4" ]; then
clear
echo Minecraft By Mojang
echo Run Script by Paul Lamb
echo www.paulscode.com
echo Launcher By Sam Smith
fi
if [ "$input" == "5" ]; then
cd
12-1/troubleshoot.sh || Failed, did you delete the 12-1 folder?
fi
if [ "$input" == "6" ]; then
cd
sudo rm -rf 12-1RPI
git clone https://github.com/ABadCoder1234/12-1RPI
sudo chmod +x 12-1RPI/OpenMinecraft
sudo mv 12-1RPI/OpenMinecraft /usr/bin/OpenMinecraft
sudo chmod +x /usr/bin/OpenMinecraft
echo Finished
fi
# Hey gamer
if [ "$input" == "c" ]; then
clear
echo  
fi
