#!/bin/bash
clear
cd
figlet Minecraft
if [ "$?" == "127" ]; then
clear 
echo Figlet not detected 
echo Download figlet? [y,n]
read -rsn1 input
if [ "$input" == "y" ]; then
sudo apt-get -y install figlet
OpenMinecraft
fi
fi
clear
figlet Minecraft
echo 1. Launch
echo 2. Launch Options -Debug-
echo 3. Advanced Settings -Login-
echo 4. Installation Troubleshooting
echo 5. Update Launcher
echo 6. Credits
echo 7. About
echo "(C)lose"
read -rsn1 input
if [ "$input" == "1" ]; then
echo Opening Minecraft
echo Keep settings all the way down!
echo Keep window default size for best performance!
sleep 2
cd Minecraft && ./runMC1_12_2_OptifineF4.sh
OpenMinecraft
fi
if [ "$input" == "2" ]; then
cd
cd ~/Minecraft && /opt/jdk/jdk1.8.0_211/bin/java -jar Minecraft.jar
OpenMinecraft
fi
if [ "$input" == "3" ]; then
sudo nano Minecraft/runMC1_12_2_OptifineF4.sh
OpenMinecraft
fi
if [ "$input" == "s" ]; then
echo You best not ruin it!
read -rsn2 input
if [ "$input" == "ok" ]; then
clear
echo ACCESS GRANTED
echo "<     >"
sleep 3
clear
echo ACCESS GRANTED
echo "<===  >"
sleep 1
clear
echo ACCESS GRANTED
echo "<=====>"
sleep 2
clear
sudo nano /usr/bin/OpenMinecraft
OpenMinecraft
fi
fi
if [ "$input" == "6" ]; then
clear
echo Minecraft By Mojang
echo Run Script by Paul Lamb
echo www.paulscode.com
echo Launcher By Sam Smith
read -rsn1 input
OpenMinecraft
fi
if [ "$input" == "4" ]; then
clear
echo If installation fails, you there may already be a Minecraft Folder. You can delete or rename it easily here.
echo Press 'd' to delete the folder
echo Press 'r' rename the folder
echo "Press any other key to do no action"
read -rsn1 input
if [ "$input" == "d" ]; then
cd
sudo rm -rf Minecraft && echo Succesfully Removed
if [ "$input" == "r" ]; then
cd
mv Minecraft minecraft-folder && echo Safely Resolved Issue
else
echo No action performed
fi
fi
OpenMinecraft
fi
if [ "$input" == "5" ]; then
cd
sudo rm -rf 12-1RPI
git clone https://github.com/ABadCoder1234/12-1RPI
sudo chmod +x 12-1RPI/OpenMinecraft
sudo mv 12-1RPI/OpenMinecraft /usr/bin/OpenMinecraft
sudo chmod +x /usr/bin/OpenMinecraft
echo Finished
OpenMinecraft
fi
if [ "$input" == "7" ]; then
clear
figlet About
if [ "$?" == "127" ]; then
clear
echo About
fi
echo "Minecraft version: 1.12.2"
echo "Optifine version: 1.12.2 F4 Ultra"
echo "Launcher Version: 1.1"
echo Press any key to continue
read -rsn1 input
fi
if [ "$input" == "c" ]; then
clear
echo  
clear
fi
